name: Verificar Mensaje de Commit

on:
  pull_request:
    types:
      - opened

jobs:
  verificar:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Comprobar Formato de Inicio de Commit
        run:         
            echo "El mensaje de commit no cumple con el formato de inicio requerido."
